on: [pull_request]
name: Benchmarking

needs:
  - workflow: Sanity Check
    run: checks

jobs:
  benchmarking:
    runs-on: ubuntu-latest
    steps:
    - name: Timeit
      run: |
        { time make > /dev/null 2>&1 ; } 2> output.txt
    - name: Post benchmark results
      run: |
        COMMENT="$(cat output.txt)"
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d "{\"body\":\"\`\`\`$COMMENT\`\`\`\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"