on: [pull_request]
name: Sanity Check
jobs:
  sanity_check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compile
      run: |
        make
        sh ./test/test.sh
    - name: Benchmarking
      run: |
        echo "GCC Build Analytics ⌚:" > output.txt
        { time make > /dev/null 2>&1 ; } 2>> output.txt
        COMMENT="$(cat output.txt)"
    - name: Benchmarking Comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: output.txt
