on: [push, pull_request]
name: Sanity Check
jobs:
  sanity_check:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compile
      run: |
        make
        sh ./test/test.sh
    - name: Benchmarking
      run: |
        { time make > /dev/null 2>&1 ; } 2> output.txt
        COMMENT="$(cat output.txt)"
    - name: Benchmarking Comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: output.txt
  # benchmarking:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'
  #   needs: sanity_check
  #   steps:
  #   - name: Timeit
  #     run: |
  #       { time make > /dev/null 2>&1 ; } 2> output.txt
  #   - name: Post benchmark results
  #     run: |
  #       COMMENT="$(cat output.txt)"
  #       curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d "{\"body\":\"\`\`\`$COMMENT\`\`\`\"}" "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
